/* JavaScript module: fake contact data */

export default [
  {
    "_id": "!tex-gabe",
    "_rev": "",
    "file_type": "contact",
    "ts_created": 1647023499833,
    "ts_updated": 1647023499833,
    "loc_subdir": "",
    "name_full": "Mr Nash Dealba",
    "name_user": "gabe",
    "birthdate": "23 Feb 2006",
    "roles": ["Admin"],
    "emails": ["gabe.wisoky@christiansen.info"],
    "phones": ["(915) 905-2130"],
    "locations": ["6375 Cozy Passage, Cordova, Texas 78180-7699"],
    "social_profiles": [""],
    "project_urls": [""],
    "team_groups": [""],
    "image_src": "",
    "bio_short": "",
    "miscellany": ""
  },
  {
    "_id": "!tex-ardith92",
    "_rev": "",
    "file_type": "contact",
    "ts_created": 1647023499833,
    "ts_updated": 1647023499833,
    "loc_subdir": "",
    "name_full": "Mr Burr Canter",
    "name_user": "ardith92",
    "birthdate": "08 Nov 2007",
    "roles": ["Lead"],
    "emails": ["ardith92@bailey.info"],
    "phones": ["(940) 566-4391"],
    "locations": ["569 Heather Stead, Holly, Texas 79075-6241"],
    "social_profiles": [""],
    "project_urls": [""],
    "team_groups": [""],
    "image_src": "",
    "bio_short": "",
    "miscellany": ""
  },
  {
    "_id": "!mon-alba",
    "_rev": "",
    "file_type": "contact",
    "ts_created": 1647023499833,
    "ts_updated": 1647023499833,
    "loc_subdir": "",
    "name_full": "Mr Jody Blum",
    "name_user": "alba",
    "birthdate": "18 Dec 2000",
    "roles": ["Lead"],
    "emails": ["alba.nicolas@ziemann.com"],
    "phones": ["(406) 416-0119"],
    "locations": ["3247 Old Grove Island, Fox Ridge, Montana 59218-7047"],
    "social_profiles": [""],
    "project_urls": [""],
    "team_groups": [""],
    "image_src": "",
    "bio_short": "",
    "miscellany": ""
  },
  {
    "_id": "!ark-ynienow",
    "_rev": "",
    "file_type": "contact",
    "ts_created": 1647023499833,
    "ts_updated": 1647023499833,
    "loc_subdir": "",
    "name_full": "Mr Akbar Showers",
    "name_user": "ynienow",
    "birthdate": "18 Aug 2005",
    "roles": [""],
    "emails": ["ynienow@jacobi.net"],
    "phones": ["(870) 743-7937"],
    "locations": ["9648 Green Subdivision, Bon Air Estates, Arkansas 72731-0189"],
    "social_profiles": [""],
    "project_urls": [""],
    "team_groups": [""],
    "image_src": "",
    "bio_short": "",
    "miscellany": ""
  },
  {
    "_id": "!iow-leanna50",
    "_rev": "",
    "file_type": "contact",
    "ts_created": 1647023499833,
    "ts_updated": 1647023499833,
    "loc_subdir": "",
    "name_full": "Ms Nitu Michener",
    "name_user": "leanna50",
    "birthdate": "17 Jun 2004",
    "roles": ["Contributor"],
    "emails": ["leanna50@gmail.com"],
    "phones": ["(712) 393-7890"],
    "locations": ["2896 Rustic Wood, Rossiter, Iowa 50528-5894"],
    "social_profiles": [""],
    "project_urls": [""],
    "team_groups": [""],
    "image_src": "",
    "bio_short": "",
    "miscellany": ""
  },
  {
    "_id": "!rho-gino88",
    "_rev": "",
    "file_type": "contact",
    "ts_created": 1647023499833,
    "ts_updated": 1647023499833,
    "loc_subdir": "",
    "name_full": "Ms Amaia Resch",
    "name_user": "gino88",
    "birthdate": "31 Aug 1999",
    "roles": ["Admin"],
    "emails": ["gino88@yahoo.com"],
    "phones": ["(401) 553-1039"],
    "locations": ["6656 Iron Panda Mount, Milroy, Rhode Island 02877-1688"],
    "social_profiles": [""],
    "project_urls": [""],
    "team_groups": [""],
    "image_src": "",
    "bio_short": "",
    "miscellany": ""
  },
  {
    "_id": "!ohi-cbashirian",
    "_rev": "",
    "file_type": "contact",
    "ts_created": 1647023499833,
    "ts_updated": 1647023499833,
    "loc_subdir": "",
    "name_full": "Mr Raphael Resch",
    "name_user": "cbashirian",
    "birthdate": "23 Oct 2006",
    "roles": ["Contributor"],
    "emails": ["cbashirian@lubowitz.com"],
    "phones": ["(567) 271-2062"],
    "locations": ["9549 Rocky Hickory Pike, Keyes Summit, Ohio 43203-2962"],
    "social_profiles": [""],
    "project_urls": [""],
    "team_groups": [""],
    "image_src": "",
    "bio_short": "",
    "miscellany": ""
  },
  {
    "_id": "!rho-klocko",
    "_rev": "",
    "file_type": "contact",
    "ts_created": 1647023499833,
    "ts_updated": 1647023499833,
    "loc_subdir": "",
    "name_full": "Mr Elias Welk",
    "name_user": "klocko",
    "birthdate": "25 Oct 1992",
    "roles": [""],
    "emails": ["klocko.federico@grimes.com"],
    "phones": ["(401) 844-0948"],
    "locations": ["1070 Misty Willow Glen, Apache Acres Trailer Park, Rhode Island 02857-9584"],
    "social_profiles": [""],
    "project_urls": [""],
    "team_groups": [""],
    "image_src": "",
    "bio_short": "",
    "miscellany": ""
  },
  {
    "_id": "!iow-ethel95",
    "_rev": "",
    "file_type": "contact",
    "ts_created": 1647023499833,
    "ts_updated": 1647023499833,
    "loc_subdir": "",
    "name_full": "Ms Cindy Knapp",
    "name_user": "ethel95",
    "birthdate": "22 May 1994",
    "roles": ["Lead"],
    "emails": ["ethel95@willms.org"],
    "phones": ["(515) 661-8492"],
    "locations": ["1458 Colonial Dale, Mud Landing, Iowa 51086-4649"],
    "social_profiles": [""],
    "project_urls": [""],
    "team_groups": [""],
    "image_src": "",
    "bio_short": "",
    "miscellany": ""
  },
  {
    "_id": "!ohi-kara",
    "_rev": "",
    "file_type": "contact",
    "ts_created": 1647023499833,
    "ts_updated": 1647023499833,
    "loc_subdir": "",
    "name_full": "Ms Edolie Knapp",
    "name_user": "kara",
    "birthdate": "07 Oct 1994",
    "roles": [""],
    "emails": ["kara.keeling@yahoo.com"],
    "phones": ["(216) 659-2668"],
    "locations": ["8621 Sleepy Mall, Pattons Corners, Ohio 45759-2387"],
    "social_profiles": [""],
    "project_urls": [""],
    "team_groups": [""],
    "image_src": "",
    "bio_short": "",
    "miscellany": ""
  }
];
